{
  'RME' => 'https://raw.githubusercontent.com/RMEx/RME/master/src',
  'custom-database' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/CustomDatabase',
  'nuki-quest-system' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/QuestSystem',
  'nuki-buzzer' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/Buzzer',
  'display-text' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/DisplayText',
  'nuki-mouse-keyboard' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/MouseAndKeyboard',
  'nuki-item-uniq' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/ObjetsUniques',
  'nuki-smooth-move' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/SmoothMove',
  'standardize-rgss' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/StandardizeRGSS',
  'tone-tester' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/ToneTester',
  'EventExtender4' => 'https://raw.githubusercontent.com/Grimimi/EventExtender4/master',
  'nuki-break-scene' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/break-scene',
  'vincent26-floor-creator' => 'https://raw.githubusercontent.com/vincent26/RM/master/Map/Etage',
  'vincent26-maze-generator' => 'https://raw.githubusercontent.com/vincent26/RM/master/Divers/Maze_Generator',
  'vincent26-limiter_inv' => 'https://raw.githubusercontent.com/vincent26/RM/master/Menu/Limiteur',
  'vincent26-storage_chest' => 'https://raw.githubusercontent.com/vincent26/RM/master/Menu/Coffre_Stockage',
  'vincent26-weapon-upgrade' => 'https://raw.githubusercontent.com/vincent26/RM/master/Combats/Weapon_Upgrade',
  'vincent26-overlay-helper' => 'https://raw.githubusercontent.com/vincent26/RM/master/Utilitaire/Aide_overlay_mapping',
  'vincent26-multi-currency' => 'https://raw.githubusercontent.com/vincent26/RM/master/Menu/Multi_Monnaie',
  'raho-useless' => 'https://raw.githubusercontent.com/hyperaho/RPGMaker/master/useless',
  'RME-tone-tester' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/RMEToneTester',
  'event-printer' => 'https://raw.githubusercontent.com/ZangtherRGSS3/Scripts/master/EventPrinter',
  'nuki-sample-script' => 'https://raw.githubusercontent.com/nukiFW/RPGMaker/master/nuki-sample-script',
  'zangther-ring-menu' => 'https://raw.githubusercontent.com/ZangtherRGSS3/Scripts/master/RingMenu'
}
